# 



# Group DocsTestWeb.Books
## DocsTestWeb.Books [/api/books]
### DocsTestWeb.Books create [POST /api/books]


+ Request create books renders books when data is valid
**POST**&nbsp;&nbsp;`/api/books`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "books": {
                "name": "some name"
              }
            }

+ Response 201

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: FmhvnJdtjxLfB2QAAZGD
            location: /api/books/80
    + Body
    
            {
              "data": {
                "name": "some name",
                "id": 80
              }
            }
### DocsTestWeb.Books index [GET /api/books]


+ Request index lists all books
**GET**&nbsp;&nbsp;`/api/books`

    + Headers
    
            accept: application/json

+ Response 200

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: FmhvnJbT4TtwGKAAAVah
    + Body
    
            {
              "data": []
            }

