# 



# Group Books API
## Books API [/api/books]
### Books API index [GET /api/books]


+ Request index lists all books
**GET**&nbsp;&nbsp;`/api/books`

    + Headers
    
            accept: application/json

+ Response 200

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: FmhwxFBrR3DTbfAAAACC
    + Body
    
            {
              "data": []
            }
### Books API create [POST /api/books]


+ Request create books renders books when data is valid
**POST**&nbsp;&nbsp;`/api/books`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "books": {
                "name": "some name"
              }
            }

+ Response 201

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: FmhwxEn2tGzCC4oAAAYB
            location: /api/books/122
    + Body
    
            {
              "data": {
                "name": "some name",
                "id": 122
              }
            }

